# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Call for papers"
#  url = ""
#  weight = 10

#[[main]]
# name = "Program"
# url = "#program"
# weight = 25

#[[main]]
# name = "Detailed program"
# url = "#talks"
# weight = 30

#[[main]]
# name = "Team"
# url = "#chairs"
# weight = 45

#[[main]]
# name = "Contact"
# url = "#contact"
# weight = 60

[[main]]
 name = "Fran√ßais"
 url = "https://acsi2023.ca"
 weight = 65

#[[main]]
#  name = "Live Stream"
#  url = "https://www.cais2020.ca/live-stream/"
#  weight = 60
